# Writes OUTPUT as a C header holding each INPUTS file as a NUL-terminated
# `static const unsigned char NAME[]`, where NAMES pairs with INPUTS. The sources stay
# byte-for-byte unchanged (the frozen runtime.js must not be edited).
#   cmake -DOUTPUT=out.h -DINPUTS="a.js;b.js" -DNAMES="a;b" -P embed_text.cmake
list(LENGTH INPUTS count)
list(LENGTH NAMES name_count)
if(NOT count EQUAL name_count)
  message(FATAL_ERROR "INPUTS and NAMES differ in length")
endif()
set(text "/* Generated by cmake/embed_text.cmake; do not edit. */\n#pragma once\n")
math(EXPR last "${count} - 1")
foreach(index RANGE ${last})
  list(GET INPUTS ${index} input)
  list(GET NAMES ${index} name)
  file(READ "${input}" hex HEX)
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex "${hex}")
  string(REGEX REPLACE "((0x..,){16})" "\\1\n    " hex "${hex}")
  string(APPEND text "static const unsigned char ${name}[] = {\n    ${hex}0x00\n};\n")
endforeach()
file(WRITE "${OUTPUT}.tmp" "${text}")
file(COPY_FILE "${OUTPUT}.tmp" "${OUTPUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUTPUT}.tmp")
